version: '3'

services:
  app:
    image: nextcloud:apache
    tty: true
    labels:
      kr.ingress.80: https://nextcloud.*
    ports:
      - 80:80
    environment:
      - POSTGRES_HOST=ep-little-night-646914.us-east-2.aws.neon.tech
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
    env_file:
      - db.env

  caddy:
    image: ditherwither/personal-site:latest
    restart: always
    tty: true
    labels:
      kr.ingress.80: https://www.*
    volumes:
      - caddy:/data
    links:
      - app:nextcloud

volumes:
  nextcloud:
  caddy: