version: '3'

services:
  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
    environment:
      - POSTGRES_HOST=ep-little-night-646914.us-east-2.aws.neon.tech
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD
    depends_on:
      - redis

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - redis

  caddy:
    build: .
    restart: always
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - caddy:/data
    links:
      - app:nextcloud

volumes:
  nextcloud:
  caddy: